name: Update Wiki Home on page creation

on:
  gollum:

jobs:
  update-home:
    permissions:
      contents: write

    runs-on: ubuntu-latest
    steps:
      - name: Checkout Wiki Repo
        uses: actions/checkout@v4
        with:
          # Faz o checkout do repositório do wiki, não do principal
          repository: ${{ github.repository }}.wiki
          # Usa o token automático do GitHub Actions para ter permissão de escrita
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Home.md
        run: |
          # O evento 'gollum' é acionado para cada página alterada.
          # A mensagem do commit geralmente é "Created PageName" ou "Updated PageName".
          commit_message=$(git log -1 --pretty=%B)

          # Extrai o nome da página da mensagem. Assume que é a última palavra.
          # Ex: "Created My-New-Page" -> "My-New-Page"
          page_name=$(echo "$commit_message" | sed -n 's/.* \([^ ]*\)$/\1/p')

          # Se não for possível extrair um nome de página, encerra o script.
          if [ -z "$page_name" ]; then
            echo "Não foi possível determinar o nome da página a partir da mensagem do commit."
            exit 0
          fi

          # Não adiciona um link para a própria página Home para evitar loops.
          if [ "$page_name" = "Home" ]; then
            echo "A alteração foi na Home.md, nenhuma atualização é necessária."
            exit 0
          fi

          echo "Página atualizada detectada: $page_name"

          # Define o cabeçalho que procuramos ou adicionamos
          header="## Últimas atualizações"

          # Garante que o arquivo Home.md exista antes de tentar modificá-lo
          touch Home.md

          # Verifica se o cabeçalho já existe em Home.md. Se não, adiciona-o.
          if ! grep -q "$header" Home.md; then
            echo "Adicionando cabeçalho '$header' ao Home.md"
            echo -e "\n$header" >> Home.md
          fi

          # Cria a linha de link em Markdown (o link da wiki não precisa de .md)
          link_line="- [${page_name}]($page_name)"

          # Verifica se o link já existe para evitar duplicatas
          if grep -qF -- "$link_line" Home.md; then
            echo "O link já existe em Home.md."
            exit 0
          fi

          echo "Adicionando link ao Home.md: $link_line"

          # Usa 'sed' para inserir a nova linha de link logo abaixo do cabeçalho.
          # A barra invertida extra antes de $link_line é para o sed interpretar corretamente.
          sed -i "/$header/a \\$link_line" Home.md

          echo "Conteúdo do Home.md atualizado:"
          cat Home.md

      - name: Commit and push changes
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Faz o commit apenas se houver mudanças reais no arquivo Home.md
          if git diff --quiet Home.md; then
             echo "Nenhuma alteração para fazer commit no wiki."
             exit 0
          fi

          git add Home.md
          git commit -m "Docs: Atualiza Home.md com link para nova página"
          git push
